apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: integration-service
spec:
  permissionClaims:
    - resource: pipelineruns
      group: tekton.dev
      identityHash: 76c72feee08da14f207db717de35faf8923aae5c1094d2049ff0a8c3e3d4817a
    - resource: applications
      group: appstudio.redhat.com
      identityHash: fbb849254fb7b845293ce356a4306342e041ff7e0ab4499f5f6f0743da2e1b14
    - resource: components
      group: appstudio.redhat.com
      identityHash: fbb849254fb7b845293ce356a4306342e041ff7e0ab4499f5f6f0743da2e1b14
    - resource: applicationsnapshots
      group: appstudio.redhat.com
      identityHash: fbb849254fb7b845293ce356a4306342e041ff7e0ab4499f5f6f0743da2e1b14
    - resource: environments
      group: appstudio.redhat.com
      identityHash: fbb849254fb7b845293ce356a4306342e041ff7e0ab4499f5f6f0743da2e1b14
    - resource: applicationsnapshotenvironmentbindings
      group: appstudio.redhat.com
      identityHash: fbb849254fb7b845293ce356a4306342e041ff7e0ab4499f5f6f0743da2e1b14
    - resource: release
      group: appstudio.redhat.com
      identityHash: 2192800c1b1199de0e171fbba5eec9fef09cdf4056fb933daf58aeb33b842348
    - resource: releaseplan
      group: appstudio.redhat.com
      identityHash: 2192800c1b1199de0e171fbba5eec9fef09cdf4056fb933daf58aeb33b842348
  latestResourceSchemas:
    - md5-bdbd79111419cb45ed5f46c858d8ff96.integrationtestscenarios.appstudio.redhat.com
