resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/redhat-appstudio/application-service/config/default?ref=fd5f11553e0f678f8c582c77abb338f4678496d1
- .tekton/


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/application-service
  newName: quay.io/redhat-appstudio/application-service
  newTag: fd5f11553e0f678f8c582c77abb338f4678496d1

configMapGenerator:
- literals:
  - GITHUB_ORG=""
  name: github-config
  behavior: replace

namespace: application-service

patches:
  - ./manager_resources_patch.yaml
