resources:
- allow-argocd-to-manage.yaml
- argocd-permissions.yaml
- https://github.com/redhat-appstudio/application-service/config/default?ref=46684055dc75b2e05899d8d38cf209de17460ace
- .tekton/


apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: quay.io/redhat-appstudio/application-service
  newName: quay.io/mkovarik/application-service
  newTag: PLNSRVCE-46

configMapGenerator:
- literals:
  - GITHUB_ORG="Michkov-test"
  name: github-config
  behavior: replace

namespace: application-service

patches:
  - ./manager_resources_patch.yaml
