---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/Michkov/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-PLNSRVCE-1424
