---
- op: replace
  path: /spec/source/repoURL
  value: https://github.com/Michkov/infra-deployments.git
- op: replace
  path: /spec/source/targetRevision
  value: preview-RAMESSESII2/upgrade-OSP-1.9
