resources:
  - allow-argocd-to-manage.yaml
  - argocd-permissions.yaml
  - https://github.com/redhat-appstudio/application-service/config/default?ref=80c3a89f639f152d6a07211e55f38a1af303984b
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
  - name: quay.io/redhat-appstudio/application-service
    newName: quay.io/redhat-appstudio/pull-request-builds
    newTag: has-c32def278a641a7a025aa9a0fbdc2bd64c439bee
configMapGenerator:
  - literals:
      - GITHUB_ORG=Michkov-test
    name: github-config
    behavior: replace
namespace: application-service
patches:
  - ./manager_resources_patch.yaml
  - ./pprof_patch.yaml
