apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ../base/external-secrets
patches:
  - path: pipelines-as-code-secret-patch.yaml
    target:
      name: pipelines-as-code-secret
      kind: ExternalSecret
      group: external-secrets.io
      version: v1beta1
images:
  - name: quay.io/redhat-appstudio/build-service
    newName: quay.io/redhat-appstudio/build-service
    newTag: 1a7effa37c3b93a85da6da0b922794b8c222dfd8
