resources:
- allow-argocd-to-manage.yaml
- tekton-pipelines-namespace.yaml
- db-execution-configmap.yaml
- https://github.com/openshift-pipelines/tektoncd-results.git/config?ref=f3b3da2e10f840a2d87cbace6702fb5615ae0ad3
- route.yaml
- ingress-annotation-role.yaml
- ingress-annotation-sa.yaml
- ingress-annotation-rb.yaml
- ingress-annotation-job.yaml

images:
- name: ko://github.com/tektoncd/results/cmd/api
  newName: quay.io/redhat-appstudio/tekton-results-api
  newTag: f3b3da2e10f840a2d87cbace6702fb5615ae0ad3
- name: ko://github.com/tektoncd/results/cmd/watcher
  newName: quay.io/redhat-appstudio/tekton-results-watcher
  newTag: f3b3da2e10f840a2d87cbace6702fb5615ae0ad3

patchesStrategicMerge:
- patch-postgres-redhat-statefulset.yaml

patches:
- path: patch-tekton-results-api-no-auth.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: tekton-results-api

namespace: tekton-pipelines

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
