---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: jvm-build-service
  namespace: jvm-build-service
spec:
  latestResourceSchemas:
  - v202210050443.artifactbuilds.jvmbuildservice.io
  - v202210050443.dependencybuilds.jvmbuildservice.io
  - v202210050443.rebuiltartifacts.jvmbuildservice.io
  - v202210050443.systemconfigs.jvmbuildservice.io
  - v202210050443.tektonwrappers.jvmbuildservice.io
  - v202210050443.userconfigs.jvmbuildservice.io
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: serviceaccounts
  - group: ""
    resource: events
  - group: ""
    identityHash: 76c72feee08da14f207db717de35faf8923aae5c1094d2049ff0a8c3e3d4817a
    resource: services
  - group: apps
    identityHash: 76c72feee08da14f207db717de35faf8923aae5c1094d2049ff0a8c3e3d4817a
    resource: deployments
  - group: tekton.dev
    identityHash: 76c72feee08da14f207db717de35faf8923aae5c1094d2049ff0a8c3e3d4817a
    resource: pipelineruns
