---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: jvm-build-service
  namespace: jvm-build-service
spec:
  latestResourceSchemas:
  - v202210050443.artifactbuilds.jvmbuildservice.io
  - v202210050443.dependencybuilds.jvmbuildservice.io
  - v202210050443.rebuiltartifacts.jvmbuildservice.io
  - v202210050443.systemconfigs.jvmbuildservice.io
  - v202210050443.tektonwrappers.jvmbuildservice.io
  - v202210050443.userconfigs.jvmbuildservice.io
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: serviceaccounts
  - group: ""
    resource: events
  - group: ""
    identityHash: cc794b5a16c6090dad08f5c1e57a3140d0d3b0543c9347aa9dccac34e25a9825
    resource: services
  - group: apps
    identityHash: cc794b5a16c6090dad08f5c1e57a3140d0d3b0543c9347aa9dccac34e25a9825
    resource: deployments
  - group: tekton.dev
    identityHash: cc794b5a16c6090dad08f5c1e57a3140d0d3b0543c9347aa9dccac34e25a9825
    resource: pipelineruns
