apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-permissions.yaml
  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/openshift?ref=d3c5c4f6791798dff38b820a461fd1de666e16e0

images:
  - name:  quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/redhat-appstudio/service-provider-integration-operator
    newTag: d3c5c4f6791798dff38b820a461fd1de666e16e0
  - name: quay.io/redhat-appstudio/service-provider-integration-oauth
    newName: quay.io/redhat-appstudio/service-provider-integration-oauth
    newTag: d3c5c4f6791798dff38b820a461fd1de666e16e0

namespace: spi-system


patches:
  - target:
      kind: Deployment
      name: spi-controller-manager
    path: operator-limits-patch.json
patchesStrategicMerge:
  - delete-shared-configuration-file.yaml
