apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spi-vault
#namePrefix: spi-

resources:
  - https://github.com/redhat-appstudio/service-provider-integration-operator/config/vault/openshift?ref=ebe2093650c957832d9ac7dfacf2820c4201d563
