apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/redhat-appstudio/managed-gitops/appstudio-shared/config/kcp?ref=11b74973df6d19b0644ab28af30dc5a97745b9ab

patchesStrategicMerge:
- apiexport-patch.yaml
