resources:
  - allow-argocd-to-manage.yaml
  - https://github.com/redhat-appstudio/image-controller/config/default?ref=8fea7b436f4ec8362a645bcf5bee14427686c83e
images:
  - name: quay.io/redhat-appstudio/image-controller
    newName: quay.io/redhat-appstudio/pull-request-builds
    newTag: image-controller-9e772b83de203ba9276450b6883834a8045f2c6d
namespace: image-controller
patches:
  - ./manager_resources_patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
