---
apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: build-service
  namespace: build-service
spec:
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: configmaps
  - group: ""
    resource: namespaces
  - group: ""
    resource: events
  - group: ""
    resource: serviceaccounts
  - group: tekton.dev
    identityHash: 72b2990e51b1931e9fee86e67091b721a8c32f407d762fc847d9d2316a988b52
    resource: pipelineruns
  - group: appstudio.redhat.com
    identityHash: ecc736485912f540a27a1a8ae608141f38621d8c481f1bf963312f641f7010f4
    resource: components
  - group: appstudio.redhat.com
    identityHash: ecc736485912f540a27a1a8ae608141f38621d8c481f1bf963312f641f7010f4
    resource: applications
