resources:
- https://raw.githubusercontent.com/stolostron/cluster-registration-operator/8feed4db1b2a6805d8f0efacaaf2f2987c7bfb6d/config/rbac/service_account.yaml
- https://raw.githubusercontent.com/stolostron/cluster-registration-operator/8feed4db1b2a6805d8f0efacaaf2f2987c7bfb6d/config/rbac/role.yaml
- https://raw.githubusercontent.com/stolostron/cluster-registration-operator/8feed4db1b2a6805d8f0efacaaf2f2987c7bfb6d/config/rbac/role_binding.yaml
- https://raw.githubusercontent.com/stolostron/cluster-registration-operator/8feed4db1b2a6805d8f0efacaaf2f2987c7bfb6d/config/rbac/leader_election_role.yaml
- https://raw.githubusercontent.com/stolostron/cluster-registration-operator/8feed4db1b2a6805d8f0efacaaf2f2987c7bfb6d/config/rbac/leader_election_role_binding.yaml
- https://raw.githubusercontent.com/stolostron/cluster-registration-operator/8feed4db1b2a6805d8f0efacaaf2f2987c7bfb6d/config/installer/installer.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: controller
  newName: quay.io/stolostron/cluster-registration-operator
  newTag: 2.5.0-d29d1a682275d44cfd9ce3eb13b1d2e2ec8f7bbb

# Adds namespace to all resources.
namespace: cluster-reg-config

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: cluster-registration-installer-
