resources:
- 0-namespace.yaml
- 1-read-cm.yaml
- 2-read-cm-binding.yaml
- e2e/

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: build-pipelines-defaults
  namespace: build-templates
  literals:
  - default_build_bundle=quay.io/redhat-appstudio-tekton-catalog/pipeline-docker-build:91ce3bb32982b85d963b99602840fead24df955b
  - hacbs_build_bundle=quay.io/redhat-appstudio-tekton-catalog/pipeline-docker-build:91ce3bb32982b85d963b99602840fead24df955b

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
