sharedSecret: blabol
serviceProviders:
- type: GitHub
  clientId: <github-client-id>
  clientSecret: <github-client-secret>
baseUrl: https://spi-oauth-route-spi-system.apps.cluster-7sggm.7sggm.sandbox742.opentlc.com
