apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-permissions.yaml
  - https://github.com/sparkoo/service-provider-integration-operator/config/default?ref=1a3763ea07aef92fd4e275b71b67aa8176307028
  - oauth_route.yaml
  - .tekton/

images:
  - name:  quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/redhat-appstudio/service-provider-integration-operator
    # 0.6.8
    newTag: next
  - name: quay.io/redhat-appstudio/service-provider-integration-oauth
    newName: quay.io/redhat-appstudio/service-provider-integration-oauth
    # 0.6.8
    newTag: next

namespace: spi-system

patches:
  - target:
      kind: ClusterRoleBinding
      name: spi-scm-kube-rbac-proxy
    path: cluster-rb-patch.json
  - target:
      kind: ClusterRoleBinding
      name: spi-scm-spiaccesstokens-for-file-retriever-server-sa
    path: cluster-rb-patch.json
  - target:
      kind: Deployment
      name: oauth-service
    path: oauth-service-deployment-patch.json
  - target:
      kind: ConfigMap
      name: shared-config
    path: config-patch.json

# we plan to use approle authentication, but it's not ready yet
# with these dummy secrets, we're satisfying spi deployments, but they're not really used
secretGenerator:
  - name: vault-approle-spi-operator
    literals:
    - role_id=dummy
    - secret_id=dummy
  - name: vault-approle-spi-oauth
    literals:
    - role_id=dummy
    - secret_id=dummy
