resources:
  - argocd-permissions.yaml
  - https://github.com/sparkoo/service-provider-integration-operator/config/default?ref=fbff599c61ee996b3e54cc0c0c1d045e73eb6f66
  - oauth_route.yaml
  - https://github.com/redhat-appstudio/service-provider-integration-scm-file-retriever/server/config/default?ref=381f7746b88019ea13d4aa42e71b01ac9bb2ec1e
  - scm_route.yaml
  - vault_role.yaml
  - vault_rolebinding.yaml
  - .tekton/

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name:  quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/mvala/spi-operator
    newTag: svpi61-vaultTokenStorage
  - name: quay.io/redhat-appstudio/service-provider-integration-oauth
    newName: quay.io/mvala/spi-oauth
    newTag: svpi61-vaultTokenStorage
  - name: quay.io/redhat-appstudio/service-provider-integration-scm-file-retriever-server
    newName:  quay.io/redhat-appstudio/service-provider-integration-scm-file-retriever-server
    newTag: 0.3.0

namespace: spi-system


patches:
  - target:
      kind: ClusterRoleBinding
      name: spi-scm-kube-rbac-proxy
    path: cluster-rb-patch.json
  - target:
      kind: ClusterRoleBinding
      name: spi-scm-spiaccesstokens-for-file-retriever-server-sa
    path: cluster-rb-patch.json
