apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-permissions.yaml
  - https://github.com/sparkoo/service-provider-integration-operator/config/default?ref=ee2f1bb50567d6d74ef526018307d0f05521e5b3
  - oauth_route.yaml
  - .tekton/

images:
  - name:  quay.io/redhat-appstudio/service-provider-integration-operator
    newName: quay.io/redhat-appstudio/service-provider-integration-operator
    # 0.6.8
    newTag: next
  - name: quay.io/redhat-appstudio/service-provider-integration-oauth
    newName: quay.io/redhat-appstudio/service-provider-integration-oauth
    # 0.6.8
    newTag: next

namespace: spi-system

patches:
  - target:
      kind: ClusterRoleBinding
      name: spi-scm-kube-rbac-proxy
    path: cluster-rb-patch.json
  - target:
      kind: ClusterRoleBinding
      name: spi-scm-spiaccesstokens-for-file-retriever-server-sa
    path: cluster-rb-patch.json
  - target:
      kind: Deployment
      name: oauth-service
    path: oauth-service-deployment-patch.json
  - target:
      kind: ConfigMap
      name: shared-config
    path: config-vaulthost-patch.json
