apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spi
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    repoURL: https://github.com/sparkoo/infra-deployments.git
    targetRevision: svpi137
