---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: has
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - kcp-name: dev
  template:
    spec:
      source:
        repoURL: https://github.com/Michkov/infra-deployments.git
        targetRevision: preview-jvm-build-service-add-argocd
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: jvm-build-service
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          - kcp-name: dev
  template:
    spec:
      source:
        repoURL: https://github.com/Michkov/infra-deployments.git
        targetRevision: preview-jvm-build-service-add-argocd
