apiVersion: apis.kcp.dev/v1alpha1
kind: APIExport
metadata:
  name: has
spec:
  permissionClaims:
  - group: ""
    resource: secrets
  - group: ""
    resource: configmaps
  - identityHash: 49e203a6e7224a8e431f574cff006510b15775a4ecb1ac0ef721cefc9561b51d
    group: "appstudio.redhat.com"
    resource: "environments"
  - identityHash: 49e203a6e7224a8e431f574cff006510b15775a4ecb1ac0ef721cefc9561b51d
    group: "appstudio.redhat.com"
    resource: "applicationsnapshotenvironmentbindings"
